---
title: "The Data Science digital nomad"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
If you travel around you meet more and more solopreneurs or digitalm nomads. We are data science. Is it possible to make a living as solopreneur digital nomad. I think yes. To be honest I am not a digital nomad, as I have family. But I try to build up a setup where I can work indepnently of the location. You need to create products for this, in our case data products. Is this realistic. Again a yes. You can create simple products. Today its very easy to deploy such products on cloud servives like AWS or Azure without having your own infrastructure. You dont need your own infrastrcuture for and you easily scale the appiclation while you grow. I created some simple data products which I sell on fiverr and I am just starting a more complex product with convolutional neural network for image aesthetics qunatification. 

What skills does a data scientist need who wants to suceed as  solopreneur.

well, first of all we data scinece skill. The knowledgle must be broad. you need be a ful stack data scientist with these skills

- statistics
- data analyis
- machine leaning
- date engineering

besides these skills you need these skills to create viable, scalable and repeatble business model.

- Identification of business opportunities
These is the easiest part as metrics are lying around verywhere. This should be your "paradedisziplin as someone you knows something with data.

- writing
   - content writing
   - copywriting
   
- design basics
  You need to dsign images for e.g Fiverr screens
  
- Outsourcing
   
   Where and what to outsource stuff

- Development of Webapplication

- Marketing

